language: cpp
cache: ccache
matrix:
  include:
# list of configurations to be attempted:
# MPI + doc
# this is the "master" one, it is going to update the manual every time
# Variable PLUMED_ALL_TESTS=yes ensures that all the regtests can be run.
# If some of them is not enabled, the whole suite will fail.
  - os: linux
    dist: trusty
    sudo: required
    env: PLUMED_CC=mpicc PLUMED_CXX=mpic++ MAKEDOC=yes PLUMED_ALL_TESTS=yes
# the following are with debug flags
  - os: linux
    dist: trusty
    sudo: required
    env: PLUMED_CC=gcc   PLUMED_CXX=g++    CONFIG_FLAGS="--enable-debug --enable-debug-glibcxx"
  - os: linux
    dist: trusty
    sudo: required
    env: PLUMED_CC=mpicc PLUMED_CXX=mpic++ CONFIG_FLAGS="--enable-debug --enable-debug-glibcxx"
# cppcheck - takes a lot of time to compile the code, so I place it closer
# to the beginning of the list
  - os: linux
    dist: trusty
    sudo: required
    env: CPPCHECK=yes CPPCHECK_VERSION=1.81
# then check with different optimization flags
  - os: linux
    dist: trusty
    sudo: required
    env: PLUMED_CC=mpicc   PLUMED_CXX=mpic++     PLUMED_CXXFLAGS=-O3 LAPACK=yes
# test using external blas with internal lapack
  - os: linux
    if: branch =~ ^test- OR type IN(pull_request)
    dist: trusty
    sudo: required
    env: PLUMED_CC=mpicc PLUMED_CXX=mpic++  PLUMED_CXXFLAGS=-O3 LAPACK=yes CONFIG_FLAGS="--disable-external-lapack"
# test using docker image.
# currently it means ubuntu 17, with gcc6
  - sudo: required
    if: branch =~ ^test- OR type IN(pull_request)
    services: docker
    env: PLUMED_DOCKER=yes
# osx serial
  - os: osx
    if: branch =~ ^test- OR type IN(pull_request)
    osx_image: xcode7.3
    env: PLUMED_CC=clang PLUMED_CXX=clang++ PLUMED_CXXFLAGS=-O3
# this should not be required. I add it since it looks like with OSX it does not work otherwise
    cache:
      directories:
      - $HOME/.ccache
# osx parallel
  - os: osx
    if: branch =~ ^test- OR type IN(pull_request)
    osx_image: xcode7.3
    env: PLUMED_CC=mpicc PLUMED_CXX=mpic++  PLUMED_CXXFLAGS=-O3
# this should not be required. I add it since it looks like with OSX it does not work otherwise
    cache:
      directories:
      - $HOME/.ccache
# osx serial macports
  - os: osx
    if: branch =~ ^test- OR type IN(pull_request)
    osx_image: xcode7.3
    env: PLUMED_MACPORTS="plumed"
    cache:
      directories:
      - $HOME/.macports-ci-ccache
# osx serial macports debug variant
  - os: osx
    if: branch =~ ^test- OR type IN(pull_request)
    osx_image: xcode7.3
    env: PLUMED_MACPORTS="plumed +allmodules"
    cache:
      directories:
      - $HOME/.macports-ci-ccache
# osx serial macports debug variant
  - os: osx
    osx_image: xcode8.3
    env: PLUMED_MACPORTS="plumed +allmodules"
    cache:
      directories:
      - $HOME/.macports-ci-ccache
# I don't put any mpi variant with macports since it takes too long to compile
## This command can be used to allow failures:
  allow_failures:
# I allow this to fail temporarily
  - env: PLUMED_DOCKER=yes
## Possible additional variables:
#   VALGRIND=yes to make valgrind tests, only when log contains string [valgrind]
install:
# setup environment to allow install on the home directory
  - export PATH="$HOME/opt/bin:$PATH"
  - export CPATH="$HOME/opt/include:$CPATH"
  - export INCLUDE="$HOME/opt/include:$INCLUDE"
  - export LIBRARY_PATH="$HOME/opt/lib:$LIBRARY_PATH"
  - export LD_LIBRARY_PATH="$HOME/opt/lib:$LD_LIBRARY_PATH"
# on travis, better dump stack trace in case there is an error
  - export PLUMED_STACK_TRACE=yes
  - export PLUMED_NUM_THREADS=2
  - ./.travis/check.log valgrind || VALGRIND=no
# update packages
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && test -z "$PLUMED_MACPORTS" ; then
      brew update > /dev/null ;
      brew install ccache ;
      export PLUMED_MPIRUN="mpirun --oversubscribe" ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
# install some package - these are fast, we install them anyway
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libmatheval-dev libfftw3-dev gsl-bin libgsl0-dev  libboost-serialization-dev ; fi
  - if test "$PLUMED_CXX" ; then ./.travis/install.xdrfile ; fi
# cppcheck:
# I use 1.71 since 1.72 seems to report a lot of false positive
  - if test "$CPPCHECK" == yes ; then  ./.travis/install.cppcheck $CPPCHECK_VERSION ; fi
# for plumedcheck I need latest gawk
  - if test "$CPPCHECK" == yes ; then  ./.travis/install.gawk 4.1.4 ; fi
# for plumedcheck I need astyle
  - if test "$CPPCHECK" == yes ; then make -j 4 -C astyle ; fi
# installation of these packages takes a lot of time
# we do it only when needed
  - if test "$PLUMED_CXX" == "mpic++" -a "$TRAVIS_OS_NAME" == "linux" ; then sudo apt-get install -y libopenmpi-dev openmpi-bin ; fi
  - if test "$PLUMED_CXX" == "mpic++" -a "$TRAVIS_OS_NAME" == "osx" ;   then brew install openmpi ; fi
  - if test "$MAKEDOC" == yes ; then sudo apt-get install -y graphviz            ; fi
# install doxygen-latex
  - if test "$MAKEDOC" == yes ; then sudo apt-get install -y doxygen-latex ; fi
# install lcov
  - if test "$MAKEDOC" == yes ; then ./.travis/install.lcov v1.13 ; fi
# then replace doxygen with the desided version
# I use 1.8.10 instead of 1.8.11 since it looks like 1.8.11 have troubles with
# non case sensitive files (it writes capitalized filenames)
  - if test "$MAKEDOC" == yes ; then ./.travis/install.doxygen Release_1_8_13 ; fi
  - if test "$VALGRIND" == yes ; then sudo apt-get install -y valgrind           ; fi
  - if test "$LAPACK" == yes ; then sudo apt-get -y install libatlas-base-dev      ; fi
# moreover, we hardcode path to dynamic library, required for xdrfile to link properly
# I do it only when LD_LIBRARY_PATH is non blank, since otherwise clang gives problems
  - if test -n "$LD_LIBRARY_PATH" ; then PLUMED_LDFLAGS="-Wl,-rpath,$LD_LIBRARY_PATH" ; fi
# macports related stuff
# configure macports
  - if test -n "$PLUMED_MACPORTS" ; then
      export COLUMNS=80 ;
      wget https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci ;
      chmod +x ./macports-ci ;
      ./macports-ci install ;
      PATH="/opt/local/bin:$PATH" ;
      make macports ;
      ./macports-ci localports macports ;
      ./macports-ci ccache ;
    fi
script:
# make sure all modules are enabled
  - CONFIG_FLAGS="$CONFIG_FLAGS --enable-modules=all"
# we enable fftw, which is off by default
  - CONFIG_FLAGS="$CONFIG_FLAGS --enable-fftw"
# enable boost_serialization to test drr module
  - CONFIG_FLAGS="$CONFIG_FLAGS --enable-boost_serialization"
  - if test "$MAKEDOC" == yes ; then CONFIG_FLAGS="$CONFIG_FLAGS --enable-pdfdoc" ; fi
  - if test "$MAKEDOC" == yes ; then CONFIG_FLAGS="$CONFIG_FLAGS --enable-gcov" ; fi
# when running lcov plumed should be compiled with -O0
  - if test "$MAKEDOC" == yes ; then PLUMED_CXXFLAGS=-O0 ; fi

# BUILD:
# this is done only if PLUMED_CXX is defined
  - if test "$PLUMED_CXX" ; then
      ccache -s ;
      ./configure CXX="ccache $(which $PLUMED_CXX)" CC=$(which $PLUMED_CC) CXXFLAGS="$PLUMED_CXXFLAGS" LDFLAGS="$PLUMED_LDFLAGS" CPPFLAGS="$PLUMED_CPPFLAGS" $CONFIG_FLAGS ;
      make -j 4 ;
      make install prefix="$HOME/opt" ;
      ccache -s ;
    fi

# build using macports
  - if test -n "$PLUMED_MACPORTS" ; then
      sudo port -N install $PLUMED_MACPORTS ;
      ./macports-ci ccache --save ;
    fi

# build docker container
  - if test "$PLUMED_DOCKER" = yes ; then make -C docker ; fi

# TEST:
  - if test "$VALGRIND" == yes ; then OPT=valgrind ; else OPT="" ; fi
# --no-print-directory make it more silent
  - if test "$PLUMED_CXX" || test -n "$PLUMED_MACPORTS" ; then make --no-print-directory -C regtest $OPT ; fi

# test with gcc6
  - if test "$PLUMED_DOCKER" = yes ; then docker run -v "$PWD/regtest":/home/plumed/regtest -it plumed /bin/bash -c "make -C regtest" ; fi
# currently, gcc6 fails for numerical reasons. Once this is fixed we can add the "make -C regtest checkfail" command below

  - if test "$MAKEDOC" == yes ; then make -C regtest copytodoc ; fi
  - if test "$MAKEDOC" == yes ; then make -C developer-doc coverage ; fi
  - if test "$MAKEDOC" == yes ; then make doc >/dev/null ; fi
  - if test "$PLUMED_CXX" || test -n "$PLUMED_MACPORTS" ; then make -C regtest checkfail ; fi

# CPPCHECK:
# this is required so as to have all the include files inplace:
# notice that this is done automatically in build
  - if test "$CPPCHECK" == yes ; then make -C src/lib/ dirslinks ; fi
# then we do cppcheck
# notice that with make codecheck we also run the maketools/plumedcheck
# script which check if coding policies are satisfied
  - if test "$CPPCHECK" == yes ; then make codecheck ; fi
after_success:
  - if test "$MAKEDOC" == yes ; then ./.travis/pushdoc ; fi 
